trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'flask-demo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'